/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "whqcmqcwurdfdscrdlwy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndocWNtcWN3dXJkZmRzY3JkbHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDE3MzksImV4cCI6MjA3MDgxNzczOX0.LHTGHLOnCi-LBD0usKo1-Jic-PZo-bis2_IFli7gnvs"